server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
#        enable_lazy_load_no_trans: true

application:
  title: shop-fullStack
  version: 1.0.0